In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("/content/grade-records.csv")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1029 entries, 0 to 1028
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1029 non-null   int64
 1   First Name        1029 non-null   object
 2   Last Name         1029 non-null   object
 3     Mid-term exams  1029 non-null   object
 4   Final exam        1029 non-null   object
 5    CW 1             1029 non-null   object
 6   CW 2              1029 non-null   object
 7   Total
Points      1029 non-null   int64
 8   Student
Average   1029 non-null   object
 9   Grade             1029 non-null   object
dtypes: int64(2), object(8)
memory usage: 80.5+ KB

In [13]:
df.head()

,Unnamed: 0,First Name,Last Name,Mid-term exams,Final exam,CW 1,CW 2,Total\nPoints,Student\nAverage,Grade
0,1,Velma,Paul,49%,66%,59%,78%,252,63.00%,D
1,2,Kibo,Mcgee,75%,75%,68%,66%,284,71.00%,C-
2,3,Louis,Underwood,98%,44%,67%,42%,251,62.75%,D-
3,4,Phyllis,Clemons,65%,45%,65%,55%,230,57.50%,F
4,5,Zenaida,Mcdowell,65%,54%,65%,54%,238,59.50%,F

In [14]:
print("\\nDataset dimensions (rows, columns):", df.shape)
print("\\nColumn names:", df.columns.tolist())

\nDataset dimensions (rows, columns): (1029, 10)
\nColumn names: ['Unnamed: 0', 'First Name', 'Last Name', '  Mid-term exams', 'Final exam', ' CW 1', 'CW 2', 'Total\nPoints', 'Student\nAverage', 'Grade']

In [15]:
print("Missing values:")
display(df.isnull().sum().to_frame("Missing Values"))
print("Duplicate rows:", df.duplicated().sum())

Missing values:

                  Missing Values
Unnamed: 0                     0
First Name                     0
Last Name                      0
  Mid-term exams               0
Final exam                     0
 CW 1                          0
CW 2                           0
Total\nPoints                  0
Student\nAverage               0
Grade                          0

Duplicate rows: 0

In [23]:
print(len(df))

1029

In [16]:
print("Duplicate Records:")
print(df.duplicated().sum())

Duplicate Records:
0

In [37]:

df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", "_", regex=True)
    .str.lower()
)

if "unnamed:_0" in df.columns:
    df.drop(columns=["unnamed:_0"], inplace=True)

print(df.columns.tolist())

display(df.head())

['first_name', 'last_name', 'mid-term_exams', 'final_exam', 'cw_1', 'cw_2', 'total_points', 'student_average', 'grade', 'full_name']

,first_name,last_name,mid-term_exams,final_exam,cw_1,cw_2,total_points,student_average,grade,full_name
0,Velma,Paul,49%,66%,59%,78%,252,63.00%,D,Velma Paul
1,Kibo,Mcgee,75%,75%,68%,66%,284,71.00%,C-,Kibo Mcgee
2,Louis,Underwood,98%,44%,67%,42%,251,62.75%,D-,Louis Underwood
3,Phyllis,Clemons,65%,45%,65%,55%,230,57.50%,F,Phyllis Clemons
4,Zenaida,Mcdowell,65%,54%,65%,54%,238,59.50%,F,Zenaida Mcdowell

In [38]:

df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", "_", regex=True)
    .str.lower()
)

# Remove the unnecessary index column
if "unnamed:_0" in df.columns:
    df.drop(columns=["unnamed:_0"], inplace=True)

print("Cleaned column names:")
print(df.columns.tolist())

display(df.head())

Cleaned column names:
['first_name', 'last_name', 'mid-term_exams', 'final_exam', 'cw_1', 'cw_2', 'total_points', 'student_average', 'grade', 'full_name']

,first_name,last_name,mid-term_exams,final_exam,cw_1,cw_2,total_points,student_average,grade,full_name
0,Velma,Paul,49%,66%,59%,78%,252,63.00%,D,Velma Paul
1,Kibo,Mcgee,75%,75%,68%,66%,284,71.00%,C-,Kibo Mcgee
2,Louis,Underwood,98%,44%,67%,42%,251,62.75%,D-,Louis Underwood
3,Phyllis,Clemons,65%,45%,65%,55%,230,57.50%,F,Phyllis Clemons
4,Zenaida,Mcdowell,65%,54%,65%,54%,238,59.50%,F,Zenaida Mcdowell

In [39]:
def calculate_statistics(data, column):
    """Calculate summary statistics for a numeric column."""


    if data[column].dtype == 'object':
        values = data[column].str.replace('%', '', regex=False).astype(float).dropna()
    else :
        values = data[column].dropna()

    if values.empty:
        return {
            "Count": 0,
            "Average": None,
            "Highest": None,
            "Lowest": None
        }

    return {
        "Count": len(values),
        "Average": round(values.mean(), 2),
        "Highest": values.max(),
        "Lowest": values.min()
    }


statistics = calculate_statistics(df, "student_average")

print("STUDENT PERFORMANCE SUMMARY")
print("-" * 35)

for key, value in statistics.items():
    print(f"{key}: {value}")

STUDENT PERFORMANCE SUMMARY
-----------------------------------
Count: 1029
Average: 64.67
Highest: 92.5
Lowest: 42.0

In [40]:
grade_counts = df["grade"].value_counts().sort_index()

grade_percentages = (
    df["grade"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

# Combine results into a summary table
grade_summary = pd.DataFrame({
    "Number_of_Students": grade_counts,
    "Percentage": grade_percentages
})

print("GRADE DISTRIBUTION")
display(grade_summary)

GRADE DISTRIBUTION

       Number_of_Students  Percentage
grade
A-                     36         3.5
B+                     71         6.9
B-                     70         6.8
C                      35         3.4
C+                     70         6.8
C-                     72         7.0
D                      72         7.0
D+                     71         6.9
D-                    106        10.3
F                     426        41.4

In [41]:
df["full_name"] = df["first_name"].str.strip() + " " + df["last_name"].str.strip()

processed_records = df[
    [
        "full_name",
        "mid-term_exams",
        "final_exam",
        "cw_1",
        "cw_2",
        "total_points",
        "student_average",
        "grade"
    ]
].copy()

display(processed_records.head(10))

,full_name,mid-term_exams,final_exam,cw_1,cw_2,total_points,student_average,grade
0,Velma Paul,49%,66%,59%,78%,252,63.00%,D
1,Kibo Mcgee,75%,75%,68%,66%,284,71.00%,C-
2,Louis Underwood,98%,44%,67%,42%,251,62.75%,D-
3,Phyllis Clemons,65%,45%,65%,55%,230,57.50%,F
4,Zenaida Mcdowell,65%,54%,65%,54%,238,59.50%,F
5,Gillian Tillman,48%,86%,48%,86%,268,67.00%,D+
6,Constance Decker,86%,45%,86%,45%,262,65.50%,D
7,Giselle Lancaster,75%,65%,75%,65%,280,70.00%,C-
8,Kirsten Walker,45%,49%,45%,56%,195,48.75%,F
9,Bob Underwood,32%,52%,32%,52%,168,42.00%,F